homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 40.3393
  longitude: -111.5709
  # Impacts weather/sunrise data
  elevation: 4551
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  customize: !include customize.yaml

frontend:

wemo:
  static:
    - 192.168.1.2

ifttt:
  key: bZ2RdMipCv-Y_mX6u3IQRc

http:
  api_password: !secret http_password

nest:
  username: danielsgeorge@gmail.com
  password: !secret nest_password

climate:
  platform: nest

camera:
  platform: foscam
  ip: 192.168.1.6
  username: admin
  password: !secret foscam_password

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

media_player:
  - platform: cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: raspberry

zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00

automation: !include automation.yaml
scene: !include scene.yaml
group: !include group.yaml

